# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer

# metadata:
#   name: letsencrypt-prod
#   namespace: easyshop
# spec:
#   acme:
#     email: shivamsingh22188@gmsil.com
#     server: https://acme-v02.api.letsencrypt.org/directory
#     privateKeySecretRef:
#       name: letsencrypt-prod-key
#     solvers:
#     - http01:
#         ingress:
#           class: nginx 
  
